

services:
  db:
    container_name: postgres_container
    image: postgres:latest
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: weather_db
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  af:
    container_name: airflow_conitainer
    image: apache/airflow:2.9.0
    ports:
      - "8000:8080"
    environment:

      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@db:5432/airflow_db
    volumes: 
      - ./airflow/dags:/opt/airflow/dags 